using System.Linq.Expressions;
using ASiNet.Data.Serialization.Exceptions;
using ASiNet.Data.Serialization.Generators.Helpers;
using ASiNet.Data.Serialization.Interfaces;
using ASiNet.Data.Serialization.Models;
using ASiNet.Data.Serialization.Models.Arrays;

namespace ASiNet.Data.Serialization.Generators;
public class ArraysModelsGenerator : IModelsGenerator
{
    public bool CanGenerateModelForType(Type type) => type.IsArray;

    public bool CanGenerateModelForType<T>() => typeof(T).IsArray;

    public SerializeModel<T> GenerateModel<T>(ISerializerContext serializeContext, in GeneratorsSettings settings)
    {
        try
        {
            var preModel = GenerateUnsafeModel<T>(settings);
            if (preModel is not null)
                return preModel;

            var model = new AutoGeneratedModel<T>();

            serializeContext.AddModel(model);

            model.SetSerializeDelegate(GenerateSerializeLambda<T>(serializeContext, settings));
            model.SetDeserializeDelegate(GenerateDeserializeLambda<T>(serializeContext, settings));
            model.SetGetSizeDelegate(GenerateGetSizeDelegate<T>(serializeContext, settings));

            return model;
        }
        catch (Exception ex)
        {
            throw new GeneratorException(ex);
        }
    }

    public SerializeObjectDelegate<T> GenerateSerializeLambda<T>(ISerializerContext serializeContext, in GeneratorsSettings settings)
    {
        var type = typeof(T);
        var itemsType = type.GetElementType()!;

        var inst = Expression.Parameter(type, "inst");
        var writer = Expression.Parameter(typeof(ISerializeWriter).MakeByRefType(), "writer");

        var model = ExpressionsHelper.GetOrGenerateModelGenerateTime(itemsType, serializeContext);
        var intModel = ExpressionsHelper.GetOrGenerateModelGenerateTime(typeof(int), serializeContext);

        var count = Expression.Parameter(typeof(int), "count");

        var body = Expression.IfThenElse(
                // CHECK NULL VALUE
                Expression.NotEqual(
                    inst,
                    Expression.Default(type)),
                Expression.Block([count],
                    ExpressionsHelper.WriteNullableByteGenerateTime(writer, 1),
                    Expression.Assign(count, GetLength(inst)),
                    ExpressionsHelper.CallSerialize(intModel, count, writer, Expression.Constant(serializeContext)),
                    SerializeElements(serializeContext, count, inst, model, writer)
                    ),
                ExpressionsHelper.WriteNullableByteGenerateTime(writer, 0)
                );

        var lambda = Expression.Lambda<SerializeObjectDelegate<T>>(body, inst, writer);
        return lambda.Compile();
    }

    public DeserializeObjectDelegate<T> GenerateDeserializeLambda<T>(ISerializerContext serializeContext, in GeneratorsSettings settings)
    {
        var type = typeof(T);
        var itemsType = type.GetElementType()!;

        var reader = Expression.Parameter(typeof(ISerializeReader).MakeByRefType(), "reader");

        var model = ExpressionsHelper.GetOrGenerateModelGenerateTime(itemsType, serializeContext);
        var intModel = ExpressionsHelper.GetOrGenerateModelGenerateTime(typeof(int), serializeContext);

        var inst = Expression.Parameter(type, "inst");
        var count = Expression.Parameter(typeof(int), "count");

        var body = Expression.Block([inst, count],
            Expression.IfThen(
                // READ NULLABLE BYTE
                Expression.Equal(
                    ExpressionsHelper.ReadNullableByteGenerateTime(reader),
                    Expression.Constant((byte)1)),

                Expression.Block(
                    Expression.Assign(count, ExpressionsHelper.CallDeserialize(intModel, reader, Expression.Constant(serializeContext))),
                    Expression.Assign(inst, Expression.NewArrayBounds(itemsType, count)),
                    DeserializeElements(serializeContext, count, inst, model, reader)
                    )
                ),

            inst);

        var lambda = Expression.Lambda<DeserializeObjectDelegate<T>>(body, reader);
        return lambda.Compile();
    }

    public GetObjectSizeDelegate<T> GenerateGetSizeDelegate<T>(ISerializerContext serializeContext, in GeneratorsSettings settings)
    {
        var type = typeof(T);
        var underlyingType = type.GetElementType()!;

        var inst = Expression.Parameter(typeof(T), "inst");
        var result = Expression.Parameter(typeof(int), "size");
        var count = Expression.Parameter(typeof(int), "count");

        var model = ExpressionsHelper.GetOrGenerateModelGenerateTime(underlyingType, serializeContext);

        var body = Expression.Block([result, count],
            Expression.Assign(result, Expression.Constant(1, typeof(int))),
            Expression.IfThen(
                Expression.NotEqual(
                    inst,
                    Expression.Default(type)),
                Expression.Block(
                    Expression.Assign(count, GetLength(inst)),
                    Expression.AddAssign(result, Expression.Constant(4, typeof(int))),
                    GetElementsSize(serializeContext, count, inst, model, result)
                    )
                ),
            result
            );

        var lambda = Expression.Lambda<GetObjectSizeDelegate<T>>(body, inst);
        return lambda.Compile();
    }

    private Expression GetLength(Expression inst) =>
        Expression.ArrayLength(inst);

    private Expression SerializeElements(ISerializerContext serializeContext, Expression count, Expression array, Expression model, Expression writer)
    {
        var i = Expression.Parameter(typeof(int), "i");
        var breakLabel = Expression.Label("LoopBreak");
        return Expression.Block([i],
            Expression.Assign(i, Expression.Constant(0)),
            Expression.Loop(
                Expression.IfThenElse(
                    Expression.Equal(i, count),
                    //
                    Expression.Break(breakLabel),
                    // ADD AND DESERIALIZE ELEMENT
                    Expression.Block(
                        ExpressionsHelper.CallSerialize(model, Expression.ArrayAccess(array, i), writer, Expression.Constant(serializeContext)),
                        Expression.AddAssign(i, Expression.Constant(1)))
                    ),
                breakLabel)
            );
    }

    private Expression DeserializeElements(ISerializerContext serializeContext, Expression count, Expression array, Expression model, Expression reader)
    {
        var i = Expression.Parameter(typeof(int), "i");
        var breakLabel = Expression.Label("LoopBreak");
        return Expression.Block([i],
            Expression.Assign(i, Expression.Constant(0)),
            Expression.Loop(
                Expression.IfThenElse(
                    Expression.Equal(i, count),
                    //
                    Expression.Break(breakLabel),
                    // ADD AND DESERIALIZE ELEMENT
                    Expression.Block(
                        Expression.Assign(Expression.ArrayAccess(array, i), ExpressionsHelper.CallDeserialize(model, reader, Expression.Constant(serializeContext))),
                        Expression.AddAssign(i, Expression.Constant(1)))
                    ),
                breakLabel)
            );
    }

    private Expression GetElementsSize(ISerializerContext serializeContext, Expression count, Expression array, Expression model, Expression result)
    {
        var i = Expression.Parameter(typeof(int), "i");
        var breakLabel = Expression.Label("LoopBreak");
        return Expression.Block([i],
            Expression.Assign(i, Expression.Constant(0)),
            Expression.Loop(
                Expression.IfThenElse(
                    Expression.Equal(i, count),
                    //
                    Expression.Break(breakLabel),
                    // ADD AND DESERIALIZE ELEMENT
                    Expression.Block(
                        Expression.AddAssign(result, ExpressionsHelper.CallGetSizeGenerateTime(model, Expression.ArrayAccess(array, i), Expression.Constant(serializeContext))),
                        Expression.AddAssign(i, Expression.Constant(1)))
                    ),
                breakLabel)
            );
    }


    private SerializeModel<T>? GenerateUnsafeModel<T>(in GeneratorsSettings settings)
    {
        if (!settings.UseUnsafeArraysModelsGenerator)
            return null;
        SerializeModel<T>? result = typeof(T).GetElementType()!.Name switch
        {
            nameof(Int32) => Cast(new Int32ArrayModel()),
            nameof(UInt32) => Cast(new UInt32ArrayModel()),
            nameof(Int16) => Cast(new Int16ArrayModel()),
            nameof(UInt16) => Cast(new UInt16ArrayModel()),
            nameof(Int64) => Cast(new Int64ArrayModel()),
            nameof(UInt64) => Cast(new UInt64ArrayModel()),
            nameof(Byte) => Cast(new ByteArrayModel()),
            nameof(SByte) => Cast(new SByteArrayModel()),
            nameof(Double) => Cast(new DoubleArrayModel()),
            nameof(Single) => Cast(new SingleArrayModel()),
            nameof(Char) => Cast(new CharArrayModel()),
            nameof(Boolean) => Cast(new BooleanArrayModel()),

            nameof(Guid) => Cast(new GuidArrayModel()),
            nameof(DateTime) => Cast(new DateTimeArrayModel()),
            _ => null,
        };

        static SerializeModel<T>? Cast(ISerializeModel model) =>
            model as SerializeModel<T>;

        return result;
    }
}
