using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ASiNet.Data.Serialization.Interfaces;

namespace ASiNet.Data.Serialization.Models;

internal class AutoGeneratedModel<T> : SerializeModel<T>, IDisposable
{
    public AutoGeneratedModel(SerializeObjectDelegate<T>? serialize = null,
               DeserializeObjectDelegate<T>? deserialize = null,
               GetObjectSizeDelegate<T>? getSize = null)
    {
        _serializeDelegate = serialize;
        _deserializeDelegate = deserialize;
        _getSizeDelegate = getSize;
    }


    public virtual bool ContainsSerializeDelegate => _serializeDelegate != null;
    public virtual bool ContainsDeserializeDelegate => _deserializeDelegate != null;
    public virtual bool ContainsGetSizeDelegate => _deserializeDelegate != null;



    private SerializeObjectDelegate<T>? _serializeDelegate;
    private DeserializeObjectDelegate<T>? _deserializeDelegate;
    private GetObjectSizeDelegate<T>? _getSizeDelegate;



    public override void SerializeObject(object? obj, in ISerializeWriter writer)
    {
        if (_serializeDelegate is null)
            throw new NullReferenceException();
        if (obj is T value)
            _serializeDelegate(value, writer);
    }

    public override object? DeserializeToObject(in ISerializeReader reader)
    {
        if (_deserializeDelegate is null)
            throw new NullReferenceException();
        return _deserializeDelegate(reader);
    }

    public override void Serialize(T obj, in ISerializeWriter writer)
    {
        if (_serializeDelegate is null)
            throw new NullReferenceException();
        _serializeDelegate(obj, writer);
    }

    public override T Deserialize(in ISerializeReader reader)
    {
        if (_deserializeDelegate is null)
            throw new NullReferenceException();
        return _deserializeDelegate(reader);
    }

    public void SetSerializeDelegate(SerializeObjectDelegate<T> set) =>
        _serializeDelegate = set;
    public void SetDeserializeDelegate(DeserializeObjectDelegate<T> get) =>
        _deserializeDelegate = get;

    public void SetGetSizeDelegate(GetObjectSizeDelegate<T> get) =>
        _getSizeDelegate = get;

    public override int ObjectSerializedSize(object obj) =>
        ObjectSerializedSize((T)obj);

    public override int ObjectSerializedSize(T obj)
    {
        if (_getSizeDelegate is null)
            throw new NullReferenceException();
        return _getSizeDelegate(obj);
    }

    public void Dispose()
    {
        _serializeDelegate = null;
        _deserializeDelegate = null;
        _getSizeDelegate = null;
        GC.SuppressFinalize(this);
    }

}
